# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies and run tests for backend
      working-directory: ./backend
      run: |
        npm install
        npm run test
    - name: Install dependencies and run tests for frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run test
